<?php

/**
 * [BEGIN_COT_EXT]
 * Hooks=tools
 * [END_COT_EXT]
 */
/**
 * plugin txtusersexport for Cotonti Siena
 * 
 * @package txtusersexport
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_langfile('txtusersexport', 'plug');

$mskin = cot_tplfile(array('txtusersexport', 'tools'), 'plug');
$t = new XTemplate($mskin);
foreach (glob($cfg['plugins_dir']."/txtusersexport/tpl/txtusersexport.*.tpl") as $filename)
{
	$filename = str_replace($cfg['plugins_dir']."/txtusersexport/tpl/txtusersexport.", "", $filename);
	$filename = htmlspecialchars(str_replace(".tpl", "", $filename));
	$t->assign(array(
		"EXP_GENERATE_XML" => $filename,
		"EXP_GENERATE_XML_URL" => cot_url('plug', 'r=txtusersexport&file='.$filename),
	));
	if (!empty($cfg['plugin']['txtusersexport']['where2']) && $cfg['plugin']['txtusersexport']['where1'] != $cfg['plugin']['txtusersexport']['where2'])
	{
		$t->assign('EXP_GENERATE_XML_URL_VAR2', cot_url('plug', 'r=txtusersexport&where=2&file='.$filename));
	}
	if (!empty($cfg['plugin']['txtusersexport']['where3']) && $cfg['plugin']['txtusersexport']['where1'] != $cfg['plugin']['txtusersexport']['where3']
		&& ($cfg['plugin']['txtusersexport']['where3'] != $cfg['plugin']['txtusersexport']['where2']))
	{
		$t->assign('EXP_GENERATE_XML_URL_VAR3', cot_url('plug', 'r=txtusersexport&where=3&file='.$filename));
	}
	$t->parse('MAIN.ROW');
}
$t->assign(array(
	"EXP_GENERATE_XML" => cot_url('plug', 'r=txtusersexport'),
));

$t->parse('MAIN');
if (COT_AJAX)
{
	$t->out('MAIN');
}
else
{
	$adminmain = $t->text('MAIN');
}
?>