<?php


/**
 * [BEGIN_COT_EXT]
 * Code=txtusersexport
 * Name=TXT Users Export
 * Description=Exports user database to txt/xml file
 * Version=1.0.0
 * Date=2011-11-10
 * Author=esclkm
 * Lock_guests=RW12345A
 * Requires_modules=page
 * [END_COT_EXT]
 * 
 * 
 * [BEGIN_COT_EXT_CONFIG]
 * where1=02:text:::where1
 * where2=03:text:::where2
 * where3=04:text:::where3
 * encoding=05:string::windows-1251:Output encoding
 * replacefrom=06:string:::Replace list, comma sep
 * replaceto=07:string:::Replace to list, comma sep
 * folder=08:string::datas/export:Save folder
 * [END_COT_EXT_CONFIG]
 *  */
/**
 * plugin txtusersexport for Cotonti Siena
 * 
 * @package txtusersexport
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>