<?php
/**
 * plugin txtpageexport for Cotonti Siena
 * 
 * @package txtpageexport
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

$L['export'] = 'Экспорт списка пользователей';

$L['cfg_where1'] = array('WHERE, вариант 1', '');
$L['cfg_where2'] = array('WHERE, вариант 2', '');
$L['cfg_where3'] = array('WHERE, вариант 3');
$L['cfg_encoding'] = array('Кодировка файла');
$L['cfg_replacefrom'] = array('Заменить, разделяя запятыми');
$L['cfg_replaceto'] = array('На что заменить, разделяя запятыми');
$L['cfg_folder'] = array('Сохранить в папку');

?>