<?php
/**
 * plugin txtpageexport for Cotonti Siena
 * 
 * @package txtpageexport
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

$L['export'] = 'Users export';

$L['cfg_where1'] = array('WHERE, var 1', '');
$L['cfg_where2'] = array('WHERE, var 2', '');
$L['cfg_where3'] = array('WHERE, var 3');
$L['cfg_encoding'] = array('File encoding');
$L['cfg_replacefrom'] = array('Replace from, comma separated');
$L['cfg_replaceto'] = array('Replace to, comma separated');
$L['cfg_folder'] = array('Save to folder');

?>