<!-- BEGIN: MAIN -->

<!-- BEGIN: ROW -->
{SEP}{EXP_ROW_NAME};	{EXP_ROW_GLUCOMETR_MODEL};	{EXP_ROW_FAMILIA}; {EXP_ROW_CLIENT_NAME}; {EXP_ROW_OTCHESTVO}; {EXP_ROW_OTKUDA_UZNALI}; {EXP_ROW_TELEPHONE_MOB}; {EXP_ROW_TELEPHONE_GOROD}; {EXP_ROW_USR_ADDRESS};
<!-- END: ROW -->

<!-- END: MAIN -->